// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/10/2024, 09:34:08
const configMerger = require("C:/Users/Lorry/Github_Desktop/nuxt_yelp1/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{"colors":{"yelp-red":"#d32323"}}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/Lorry/Github_Desktop/nuxt_yelp1/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lorry/Github_Desktop/nuxt_yelp1/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lorry/Github_Desktop/nuxt_yelp1/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lorry/Github_Desktop/nuxt_yelp1/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lorry/Github_Desktop/nuxt_yelp1/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lorry/Github_Desktop/nuxt_yelp1/plugins/**/*.{js,ts,mjs}","C:/Users/Lorry/Github_Desktop/nuxt_yelp1/composables/**/*.{js,ts,mjs}","C:/Users/Lorry/Github_Desktop/nuxt_yelp1/utils/**/*.{js,ts,mjs}","C:/Users/Lorry/Github_Desktop/nuxt_yelp1/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lorry/Github_Desktop/nuxt_yelp1/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Lorry/Github_Desktop/nuxt_yelp1/app.config.{js,ts,mjs}"] }));

module.exports = config
