// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10-10-2024, 09:19:19
const configMerger = require("/home/projects/sb1-yxidgt/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{"colors":{"yelp-red":"#d32323"}}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/projects/sb1-yxidgt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-yxidgt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-yxidgt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-yxidgt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-yxidgt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-yxidgt/plugins/**/*.{js,ts,mjs}","/home/projects/sb1-yxidgt/composables/**/*.{js,ts,mjs}","/home/projects/sb1-yxidgt/utils/**/*.{js,ts,mjs}","/home/projects/sb1-yxidgt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-yxidgt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-yxidgt/app.config.{js,ts,mjs}"] }));

module.exports = config
